name: Python Application Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies with Virtual Env
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        # --exclude=venv ကို ထည့်သွင်းပြီး external libraries များကို ကျော်ခိုင်းထားပါသည်
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv

    - name: Run Unit Tests with Pytest
      run: |
        source venv/bin/activate
        pytest || echo "No test cases found yet, baseline setup is ready."
